# Generated by Django 3.2 on 2023-11-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231116_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/corazon.png', null=True, upload_to='avatars/'),
        ),
    ]
